version: '3.8'
services:
  sftp:
    image: atmoz/sftp:latest
    container_name: sftp-server
    ports:
      - "2222:22"
    volumes:
      - ./sftp-data:/home/user/upload
    environment:
      - SFTP_USERS=user:password:1001
    # SFTP_USERS format: user:pass:uid[:gid[:dir]]
    # This creates user 'foo' with password 'pass', UID 1001, and home dir /home/foo
    restart: unless-stopped
